import {
  baseCompatibility,
  commonChildrenProp,
  commonClassNameProp,
  commonIconProp,
  commonLabelProp,
  commonSizeProp,
  commonToneProp,
  commonValueProp,
  commonVariantProp,
  type RegistryComponent,
} from './shared';

export const feedbackComponents: RegistryComponent[] = [
  {
    id: 'badge',
    slug: 'badge',
    displayName: 'Badge',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'feedback',
    description: 'Compact inline label conveying status, count, or category.',
    status: 'stable',
    tags: ['status', 'label'],
    props: [
      commonToneProp,
      commonVariantProp,
      commonSizeProp,
      commonClassNameProp,
      commonChildrenProp,
      commonIconProp,
      {
        name: 'dot',
        type: 'boolean',
        category: 'style',
        editingSurface: 'quick-edit',
        description: 'Shows a coloured dot indicator instead of text.',
        defaultValue: 'false',
      },
    ],
    slots: ['default'],
    events: [],
    states: ['default'],
    a11y: {
      keyboard: [],
      focusBehavior: 'Non-interactive; not focusable.',
      screenReaderNotes: [
        'Do not rely on color alone to convey status — include visible text.',
        'For dot variant, provide aria-label describing the status.',
      ],
      invalidCombinations: ['dot=true without aria-label or adjacent text'],
      localizationNotes: [
        'Status labels must be translatable; avoid icon-only status.',
      ],
    },
    responsiveBehavior: ['inline', 'does not wrap'],
    styleHooks: ['badge.bg', 'badge.color', 'badge.border', 'badge.radius'],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: true,
    },
    recipes: [
      {
        id: 'status-badge',
        label: 'Status Badge',
        description: 'Inline status indicator on a table row or card.',
        requiredProps: ['children'],
        recommendedDefaults: { tone: 'success', variant: 'soft' },
        doExample: '<Badge tone="success">Active</Badge>',
        dontExample: '<Badge tone="success" dot />',
      },
    ],
    antiPatterns: [
      {
        id: 'color-only-status',
        description: 'Conveying status using color without text.',
        reason:
          'Fails WCAG 1.4.1 (Use of Color); color-blind users cannot distinguish states.',
        fix: 'Always include text label; use dot variant only with accompanying visible text or aria-label.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'alert',
    slug: 'alert',
    displayName: 'Alert',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'feedback',
    description:
      'Inline contextual message with optional title, icon, and dismissal.',
    status: 'stable',
    tags: ['feedback', 'message', 'notification'],
    props: [
      commonToneProp,
      commonVariantProp,
      commonClassNameProp,
      commonChildrenProp,
      {
        name: 'title',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Optional bold title above the message body.',
      },
      {
        name: 'icon',
        type: 'ReactNode',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Leading icon; defaults to tone-appropriate icon.',
      },
      {
        name: 'dismissible',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Shows a dismiss button.',
        defaultValue: 'false',
      },
      {
        name: 'onDismiss',
        type: '(event: React.MouseEvent) => void',
        category: 'behavior',
        editingSurface: 'hidden',
        semantics: 'computed',
        description: 'Dismiss handler; required when dismissible=true.',
      },
    ],
    slots: ['default', 'action'],
    events: ['onDismiss'],
    states: ['default', 'dismissed'],
    a11y: {
      role: 'alert',
      ariaRequired: [],
      keyboard: [
        'Tab to dismiss button when dismissible=true',
        'Enter/Space to dismiss',
      ],
      focusBehavior:
        'Dynamically injected alerts use role="alert" (live region). Persistent alerts are static.',
      screenReaderNotes: [
        'Dynamically inserted alerts are announced automatically via role="alert".',
        'Avoid injecting multiple alerts simultaneously as live regions may overlap.',
        'Dismiss button requires aria-label="Dismiss alert" or equivalent.',
      ],
      invalidCombinations: ['dismissible=true without onDismiss handler'],
    },
    responsiveBehavior: [
      'full width',
      'stacks vertically with adjacent alerts',
    ],
    styleHooks: ['alert.bg', 'alert.color', 'alert.border', 'alert.icon.color'],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: true,
    },
    recipes: [
      {
        id: 'alert-banner',
        label: 'Alert Banner',
        description:
          'Full-width inline alert for form-level or page-level feedback.',
        requiredProps: ['children'],
        recommendedDefaults: { tone: 'error', variant: 'soft' },
        a11yCaveats: [
          'Use role="alert" for dynamically rendered alerts so screen readers announce them.',
        ],
      },
    ],
    antiPatterns: [
      {
        id: 'alert-as-toast',
        description: 'Using Alert as an auto-dismissing floating notification.',
        reason:
          'Alert is an inline component; use a Toast/Notification system for floating messages.',
        fix: 'Use a dedicated Toast component with aria-live="polite".',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'progress',
    slug: 'progress',
    displayName: 'Progress',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'feedback',
    description: 'Progress indicator for bounded tasks.',
    status: 'stable',
    tags: ['status', 'feedback'],
    props: [commonValueProp, commonLabelProp, commonClassNameProp],
    slots: ['bar'],
    events: [],
    states: ['default'],
    a11y: {
      role: 'progressbar',
      keyboard: [],
      focusBehavior: 'Non-interactive; not focusable.',
      screenReaderNotes: ['Expose numeric progress via aria-valuenow.'],
    },
    responsiveBehavior: ['fluid width'],
    styleHooks: ['progress.bg', 'progress.bar'],
    builder: { editingSurface: 'prop-driven', allowChildren: false },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'tag',
    slug: 'tag',
    displayName: 'Tag',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'feedback',
    description: 'Inline tag with optional removal action.',
    status: 'stable',
    tags: ['label', 'chip'],
    props: [commonChildrenProp, commonIconProp, commonClassNameProp],
    slots: ['default', 'icon'],
    events: ['onRemove'],
    states: ['default', 'removable'],
    a11y: {
      keyboard: ['Tab', 'Enter', 'Space'],
      focusBehavior: 'Remove button receives focus when present.',
      screenReaderNotes: ['Removal action must have a clear accessible label.'],
    },
    responsiveBehavior: ['inline'],
    styleHooks: ['tag.bg', 'tag.color'],
    builder: { editingSurface: 'prop-driven', allowChildren: true },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'empty-state',
    slug: 'empty-state',
    displayName: 'EmptyState',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'feedback',
    description: 'Placeholder shown when content is absent.',
    status: 'stable',
    tags: ['empty', 'placeholder'],
    props: [commonChildrenProp, commonClassNameProp],
    slots: ['icon', 'action'],
    events: [],
    states: ['default'],
    a11y: {
      role: 'status',
      keyboard: [],
      focusBehavior: 'Non-interactive; not focusable.',
      screenReaderNotes: ['Use clear title and action for recovery.'],
    },
    responsiveBehavior: ['stack'],
    styleHooks: ['empty-state.icon'],
    builder: { editingSurface: 'section-block', allowChildren: true },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
];
