import {
  baseCompatibility,
  commonClassNameProp,
  commonDefaultValueProp,
  commonDescriptionProp,
  commonDisabledProp,
  commonErrorProp,
  commonFullWidthProp,
  commonIconProp,
  commonLabelProp,
  commonOnChangeProp,
  commonRequiredProp,
  commonSizeProp,
  commonValueProp,
  commonVariantProp,
  interactiveRule,
  type RegistryComponent,
} from './shared';

export const formsComponents: RegistryComponent[] = [
  {
    id: 'input',
    slug: 'input',
    displayName: 'Input',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Single-line text input field.',
    status: 'stable',
    tags: ['form', 'input', 'interactive'],
    props: [
      commonLabelProp,
      commonDescriptionProp,
      commonErrorProp,
      commonRequiredProp,
      commonDisabledProp,
      commonSizeProp,
      commonVariantProp,
      commonFullWidthProp,
      commonClassNameProp,
      commonValueProp,
      commonDefaultValueProp,
      commonOnChangeProp,
      commonIconProp,
      {
        name: 'placeholder',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Placeholder text shown when value is empty.',
      },
      {
        name: 'type',
        type: 'string',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description:
          'HTML input type (text | email | password | number | search | tel | url).',
        defaultValue: 'text',
      },
      {
        name: 'autoComplete',
        type: 'string',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'HTML autocomplete attribute.',
      },
      {
        name: 'maxLength',
        type: 'number',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Maximum number of characters.',
      },
      {
        name: 'readOnly',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Makes the field read-only.',
        defaultValue: 'false',
      },
    ],
    slots: ['leading', 'trailing'],
    events: ['onChange', 'onBlur', 'onFocus', 'onKeyDown'],
    states: ['default', 'focus', 'error', 'disabled', 'readOnly'],
    a11y: {
      role: 'textbox',
      ariaRequired: ['aria-label or associated <label>'],
      keyboard: ['Tab to focus', 'Type to input', 'Escape to clear optional'],
      focusBehavior: 'Focusable via Tab. Visible focus ring required.',
      screenReaderNotes: [
        'Every Input must have an associated visible label or aria-label.',
        'Error message must be linked via aria-describedby.',
        'Placeholder is not a substitute for label.',
        'required=true should also set aria-required="true".',
      ],
      invalidCombinations: [
        'no label and no aria-label',
        'error without error message text',
      ],
      localizationNotes: [
        'placeholder and label must be translatable; avoid English-only defaults.',
      ],
    },
    responsiveBehavior: ['fullWidth optional', 'min touch target height 44px'],
    styleHooks: [
      'input.bg',
      'input.border',
      'input.color',
      'input.focus.ring',
      'input.error.border',
    ],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: false,
      insertionRules: interactiveRule,
    },
    recipes: [
      {
        id: 'form-field-input',
        label: 'Standard Form Field Input',
        description:
          'Labelled input with optional description and error message.',
        requiredProps: ['label'],
        recommendedDefaults: { size: 'md', fullWidth: true },
        a11yCaveats: [
          'Always provide label; do not rely on placeholder alone.',
        ],
        doExample: '<Input label="Email address" type="email" required />',
        dontExample: '<Input placeholder="Email address" />',
      },
    ],
    antiPatterns: [
      {
        id: 'placeholder-as-label',
        description: 'Using placeholder instead of a visible label.',
        reason: 'Placeholder disappears on focus; fails WCAG 1.3.1 and 3.3.2.',
        fix: 'Always use label prop or an associated <label> element.',
      },
      {
        id: 'uncontrolled-controlled-mismatch',
        description: 'Providing both value and defaultValue.',
        reason:
          'React will throw a warning and component behaviour is undefined.',
        fix: 'Use either value+onChange (controlled) or defaultValue (uncontrolled).',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'text-area',
    slug: 'text-area',
    displayName: 'TextArea',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Multi-line text input field.',
    status: 'stable',
    tags: ['form', 'input', 'interactive', 'multiline'],
    props: [
      commonLabelProp,
      commonDescriptionProp,
      commonErrorProp,
      commonRequiredProp,
      commonDisabledProp,
      commonSizeProp,
      commonFullWidthProp,
      commonClassNameProp,
      commonValueProp,
      commonDefaultValueProp,
      commonOnChangeProp,
      {
        name: 'placeholder',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Placeholder text.',
      },
      {
        name: 'rows',
        type: 'number',
        category: 'layout',
        editingSurface: 'layout-edit',
        description: 'Initial visible row count.',
        defaultValue: '3',
      },
      {
        name: 'maxLength',
        type: 'number',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Maximum character count.',
      },
      {
        name: 'resize',
        type: 'string',
        category: 'layout',
        editingSurface: 'layout-edit',
        description: 'Resize behaviour (none | vertical | horizontal | both).',
        defaultValue: 'vertical',
      },
      {
        name: 'readOnly',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Makes the field read-only.',
        defaultValue: 'false',
      },
    ],
    slots: [],
    events: ['onChange', 'onBlur', 'onFocus', 'onKeyDown'],
    states: ['default', 'focus', 'error', 'disabled', 'readOnly'],
    a11y: {
      role: 'textbox',
      ariaRequired: [
        'aria-label or associated <label>',
        'aria-multiline="true" (implicit on <textarea>)',
      ],
      keyboard: ['Tab to focus', 'Type to input'],
      focusBehavior: 'Focusable via Tab.',
      screenReaderNotes: [
        'Requires visible label or aria-label.',
        'Error message linked via aria-describedby.',
        'Character count (if shown) should update aria-live region.',
      ],
      invalidCombinations: ['no label and no aria-label'],
      localizationNotes: ['placeholder and label must be translatable.'],
    },
    responsiveBehavior: ['fullWidth optional', 'min touch target height 44px'],
    styleHooks: [
      'textarea.bg',
      'textarea.border',
      'textarea.color',
      'textarea.focus.ring',
      'textarea.error.border',
    ],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: false,
      insertionRules: interactiveRule,
    },
    recipes: [
      {
        id: 'notes-textarea',
        label: 'Notes Field',
        description: 'Resizable multi-line notes input with character count.',
        requiredProps: ['label'],
        recommendedDefaults: { rows: 4, resize: 'vertical', fullWidth: true },
      },
    ],
    antiPatterns: [
      {
        id: 'placeholder-as-label',
        description: 'Using placeholder instead of a visible label.',
        reason: 'Placeholder disappears on focus; fails WCAG 1.3.1.',
        fix: 'Always provide label prop.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'select',
    slug: 'select',
    displayName: 'Select',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description:
      'Dropdown selection field backed by native <select> or a custom listbox.',
    status: 'stable',
    tags: ['form', 'dropdown', 'interactive'],
    props: [
      commonLabelProp,
      commonDescriptionProp,
      commonErrorProp,
      commonRequiredProp,
      commonDisabledProp,
      commonSizeProp,
      commonFullWidthProp,
      commonClassNameProp,
      commonValueProp,
      commonDefaultValueProp,
      commonOnChangeProp,
      {
        name: 'options',
        type: 'string',
        category: 'data',
        editingSurface: 'advanced-edit',
        required: true,
        description:
          'Array of { value: string; label: string; disabled?: boolean } option objects.',
      },
      {
        name: 'placeholder',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Placeholder option shown when no value is selected.',
      },
      {
        name: 'multiple',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Allows multiple selections.',
        defaultValue: 'false',
      },
    ],
    slots: ['option'],
    events: ['onChange', 'onBlur', 'onFocus'],
    states: ['default', 'focus', 'error', 'disabled'],
    a11y: {
      role: 'combobox',
      ariaRequired: [
        'aria-label or associated <label>',
        'aria-expanded on custom listbox trigger',
      ],
      keyboard: [
        'Tab to focus',
        'Arrow keys to navigate options',
        'Enter/Space to select',
        'Escape to close',
      ],
      focusBehavior: 'Focusable via Tab. Focus moves into listbox when opened.',
      screenReaderNotes: [
        'Requires visible label or aria-label.',
        'Custom listbox must implement ARIA combobox or listbox pattern fully.',
        'Selected option announced on change.',
      ],
      invalidCombinations: [
        'no label and no aria-label',
        'empty options array',
      ],
    },
    responsiveBehavior: ['fullWidth optional'],
    styleHooks: [
      'select.bg',
      'select.border',
      'select.color',
      'select.focus.ring',
    ],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: false,
      insertionRules: interactiveRule,
    },
    recipes: [
      {
        id: 'filter-select',
        label: 'Filter Select',
        description: 'Select used as a filter control in a table toolbar.',
        requiredProps: ['label', 'options'],
        recommendedDefaults: { size: 'sm', placeholder: 'All' },
      },
    ],
    antiPatterns: [
      {
        id: 'select-no-label',
        description: 'Select without a visible label.',
        reason: 'Purpose is unclear for screen reader and keyboard users.',
        fix: 'Always provide label prop or associated <label>.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'checkbox',
    slug: 'checkbox',
    displayName: 'Checkbox',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Binary or indeterminate toggle for boolean form values.',
    status: 'stable',
    tags: ['form', 'toggle', 'interactive'],
    props: [
      commonLabelProp,
      commonDescriptionProp,
      commonErrorProp,
      commonRequiredProp,
      commonDisabledProp,
      commonClassNameProp,
      {
        name: 'checked',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Controlled checked state.',
        defaultValue: 'false',
      },
      {
        name: 'defaultChecked',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Uncontrolled initial checked state.',
        defaultValue: 'false',
      },
      {
        name: 'indeterminate',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Indeterminate/partial selection state.',
        defaultValue: 'false',
      },
      {
        name: 'onChange',
        type: '(checked: boolean) => void',
        category: 'behavior',
        editingSurface: 'hidden',
        semantics: 'computed',
        description: 'Change handler.',
      },
    ],
    slots: [],
    events: ['onChange'],
    states: ['default', 'checked', 'indeterminate', 'focus', 'disabled'],
    a11y: {
      role: 'checkbox',
      ariaRequired: ['aria-checked', 'aria-label or associated <label>'],
      keyboard: ['Tab to focus', 'Space to toggle'],
      focusBehavior: 'Focusable via Tab. Space toggles state.',
      screenReaderNotes: [
        'Label must describe what is being toggled.',
        'Indeterminate state must be set via aria-checked="mixed".',
        'Group of checkboxes should be wrapped in <fieldset> with <legend>.',
      ],
      invalidCombinations: [
        'no label and no aria-label',
        'indeterminate + checked simultaneously',
      ],
    },
    responsiveBehavior: ['min touch target 44×44px'],
    styleHooks: [
      'checkbox.bg',
      'checkbox.border',
      'checkbox.check.color',
      'checkbox.focus.ring',
    ],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: false,
      insertionRules: interactiveRule,
    },
    recipes: [
      {
        id: 'form-checkbox',
        label: 'Form Checkbox',
        description: 'Labelled checkbox inside a form.',
        requiredProps: ['label'],
        recommendedDefaults: {},
        doExample: '<Checkbox label="I agree to the terms" required />',
        dontExample: '<Checkbox />',
      },
    ],
    antiPatterns: [
      {
        id: 'checkbox-no-label',
        description: 'Checkbox without a visible label.',
        reason: 'Purpose is opaque to screen reader users.',
        fix: 'Always provide label prop.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'radio-button',
    slug: 'radio-button',
    displayName: 'RadioButton',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Single option within an exclusive-choice radio group.',
    status: 'stable',
    tags: ['form', 'radio', 'interactive'],
    props: [
      commonLabelProp,
      commonDescriptionProp,
      commonRequiredProp,
      commonDisabledProp,
      commonClassNameProp,
      {
        name: 'value',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        required: true,
        description: 'Value submitted with the form when selected.',
      },
      {
        name: 'checked',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Controlled checked state.',
      },
      {
        name: 'defaultChecked',
        type: 'boolean',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Uncontrolled initial checked state.',
        defaultValue: 'false',
      },
      {
        name: 'name',
        type: 'string',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Radio group name binding for native form behaviour.',
      },
      {
        name: 'onChange',
        type: '(value: string) => void',
        category: 'behavior',
        editingSurface: 'hidden',
        semantics: 'computed',
        description: 'Change handler.',
      },
    ],
    slots: [],
    events: ['onChange'],
    states: ['default', 'checked', 'focus', 'disabled'],
    a11y: {
      role: 'radio',
      ariaRequired: ['aria-checked', 'name attribute for grouping'],
      keyboard: [
        'Tab to enter group',
        'Arrow keys to move between options',
        'Space to select',
      ],
      focusBehavior:
        'Tab moves into the group; arrow keys navigate within the group (roving tabindex pattern).',
      screenReaderNotes: [
        'RadioButtons must be grouped inside a <fieldset> with <legend> describing the group.',
        'Each option must have a label.',
      ],
      invalidCombinations: [
        'RadioButton without a parent group / fieldset',
        'no label',
      ],
    },
    responsiveBehavior: ['min touch target 44×44px'],
    styleHooks: [
      'radio.bg',
      'radio.border',
      'radio.dot.color',
      'radio.focus.ring',
    ],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: false,
      insertionRules: interactiveRule,
    },
    recipes: [
      {
        id: 'radio-group',
        label: 'Radio Group',
        description: 'Group of RadioButton inside a fieldset with legend.',
        requiredProps: ['value', 'label'],
        recommendedDefaults: {},
      },
    ],
    antiPatterns: [
      {
        id: 'isolated-radio',
        description: 'RadioButton used outside of a named group.',
        reason:
          'Arrow-key navigation and form submission are broken without name grouping.',
        fix: 'Always place RadioButtons in a group with matching name or a RadioGroup wrapper.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'switch',
    slug: 'switch',
    displayName: 'Switch',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Binary toggle control.',
    status: 'stable',
    tags: ['form', 'toggle'],
    props: [commonLabelProp, commonDescriptionProp, commonDisabledProp],
    slots: ['thumb'],
    events: ['onCheckedChange'],
    states: ['unchecked', 'checked', 'disabled'],
    a11y: {
      role: 'switch',
      keyboard: ['Space', 'Enter'],
      focusBehavior: 'Focusable via Tab.',
      screenReaderNotes: ['Label should describe the setting being toggled.'],
    },
    responsiveBehavior: ['touch friendly'],
    styleHooks: ['switch.track', 'switch.thumb'],
    builder: { editingSurface: 'prop-driven', allowChildren: false },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'color-picker',
    slug: 'color-picker',
    displayName: 'ColorPicker',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Color input with hex and preview feedback.',
    status: 'stable',
    tags: ['color', 'input'],
    props: [commonValueProp, commonOnChangeProp, commonClassNameProp],
    slots: ['preview'],
    events: ['onChange', 'onValueChange'],
    states: ['default'],
    a11y: {
      role: 'group',
      keyboard: ['Tab', 'Type', 'Arrow keys in native color input'],
      focusBehavior: 'Native color and text inputs are focusable.',
      screenReaderNotes: [
        'Provide context if color value has business meaning.',
      ],
    },
    responsiveBehavior: ['stack'],
    styleHooks: ['color-picker.border'],
    builder: { editingSurface: 'prop-driven', allowChildren: false },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'combo-box',
    slug: 'combo-box',
    displayName: 'ComboBox',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Searchable single-select listbox.',
    status: 'stable',
    tags: ['select', 'search'],
    props: [commonValueProp, commonOnChangeProp, commonClassNameProp],
    slots: ['input', 'listbox'],
    events: ['onChange', 'onValueChange'],
    states: ['closed', 'open', 'filtering'],
    a11y: {
      role: 'combobox',
      keyboard: ['ArrowDown', 'ArrowUp', 'Enter', 'Escape'],
      focusBehavior: 'Input receives focus and manages listbox selection.',
      screenReaderNotes: ['Link input to listbox with aria-controls.'],
    },
    responsiveBehavior: ['fullWidth optional'],
    styleHooks: ['combo-box.border'],
    builder: { editingSurface: 'prop-driven', allowChildren: false },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'file-upload',
    slug: 'file-upload',
    displayName: 'FileUpload',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Drag-and-drop file upload zone.',
    status: 'stable',
    tags: ['upload', 'files'],
    props: [commonClassNameProp],
    slots: ['dropzone'],
    events: ['onChange', 'onFilesChange'],
    states: ['empty', 'over', 'populated'],
    a11y: {
      role: 'group',
      keyboard: ['Tab', 'Space', 'Enter'],
      focusBehavior: 'Native file input remains focusable.',
      screenReaderNotes: ['Describe accepted file types and size limits.'],
    },
    responsiveBehavior: ['stack'],
    styleHooks: ['file-upload.border'],
    builder: { editingSurface: 'layout-container', allowChildren: true },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'otp-input',
    slug: 'otp-input',
    displayName: 'OTPInput',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description: 'Multi-slot one-time password input.',
    status: 'stable',
    tags: ['otp', 'verification'],
    props: [commonValueProp, commonOnChangeProp, commonClassNameProp],
    slots: ['slot'],
    events: ['onChange', 'onValueChange'],
    states: ['default'],
    a11y: {
      role: 'group',
      keyboard: ['Tab', 'Backspace', 'Digits'],
      focusBehavior: 'Sequential slot focus.',
      screenReaderNotes: ['Treat each slot as part of one verification code.'],
    },
    responsiveBehavior: ['inline wrap'],
    styleHooks: ['otp-input.border'],
    builder: { editingSurface: 'prop-driven', allowChildren: false },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'slider',
    slug: 'slider',
    displayName: 'Slider',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'forms',
    description:
      'Range input for selecting a numeric value from a continuous range.',
    status: 'stable',
    tags: ['form', 'range', 'input'],
    props: [
      {
        name: 'value',
        type: 'number',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Controlled value.',
      },
      {
        name: 'defaultValue',
        type: 'number',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Uncontrolled initial value.',
      },
      {
        name: 'min',
        type: 'number',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Minimum value.',
        defaultValue: '0',
      },
      {
        name: 'max',
        type: 'number',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Maximum value.',
        defaultValue: '100',
      },
      {
        name: 'step',
        type: 'number',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Step increment.',
        defaultValue: '1',
      },
      {
        name: 'onChange',
        type: '(value: number[]) => void',
        category: 'behavior',
        editingSurface: 'hidden',
        semantics: 'computed',
        description: 'Change handler.',
      },
      commonClassNameProp,
    ],
    slots: ['thumb', 'track'],
    events: ['onChange', 'onValueChange'],
    states: ['default', 'focus', 'disabled'],
    a11y: {
      role: 'slider',
      ariaRequired: [
        'aria-valuemin',
        'aria-valuemax',
        'aria-valuenow',
        'aria-label',
      ],
      keyboard: [
        'ArrowRight / ArrowUp to increase',
        'ArrowLeft / ArrowDown to decrease',
        'Home to min',
        'End to max',
      ],
      focusBehavior: 'Thumb is focusable. Tab enters the slider.',
      screenReaderNotes: [
        'Slider thumb must have aria-label describing what the value controls.',
        'Value changes must be announced via aria-valuenow updates.',
      ],
      invalidCombinations: ['slider without aria-label on thumb'],
    },
    responsiveBehavior: ['fullWidth optional'],
    styleHooks: ['slider.track', 'slider.range', 'slider.thumb'],
    builder: { editingSurface: 'prop-driven', allowChildren: false },
    recipes: [
      {
        id: 'volume-slider',
        label: 'Volume Slider',
        description: 'Simple single-thumb slider for volume control.',
        requiredProps: ['value'],
        recommendedDefaults: { min: 0, max: 100, step: 1 },
      },
    ],
    antiPatterns: [
      {
        id: 'slider-without-label',
        description: 'Slider without an accessible label.',
        reason:
          'Screen reader users cannot determine what the slider controls.',
        fix: 'Always provide aria-label on the thumb or an associated visible label.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
];
