import {
  baseCompatibility,
  commonClassNameProp,
  commonLabelProp,
  commonSizeProp,
  commonToneProp,
  type RegistryComponent,
} from './shared';

export const mediaComponents: RegistryComponent[] = [
  {
    id: 'avatar',
    slug: 'avatar',
    displayName: 'Avatar',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'media',
    description:
      'User or entity visual identity — image, initials, or icon fallback.',
    status: 'stable',
    tags: ['user', 'image', 'profile'],
    props: [
      {
        name: 'src',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Image source URL.',
      },
      {
        name: 'alt',
        type: 'string',
        category: 'accessibility',
        editingSurface: 'advanced-edit',
        description: 'Accessible alt text for the image.',
        required: true,
      },
      {
        name: 'name',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        description: 'Name used to derive initials fallback.',
      },
      commonSizeProp,
      commonToneProp,
      commonClassNameProp,
      {
        name: 'shape',
        type: 'string',
        category: 'style',
        editingSurface: 'quick-edit',
        description: 'Shape of the avatar (circle | square).',
        defaultValue: 'circle',
      },
      {
        name: 'status',
        type: 'string',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Presence indicator (online | away | busy | offline).',
      },
    ],
    slots: ['fallback'],
    events: [],
    states: ['default', 'loading', 'error'],
    a11y: {
      role: 'img',
      ariaRequired: ['alt when src is set'],
      keyboard: [],
      focusBehavior: 'Non-interactive; not focusable.',
      screenReaderNotes: [
        'alt must describe the person or entity, not the visual style.',
        'Decorative avatars use alt="".',
        'Status indicator must be communicated via aria-label or visually-hidden text.',
      ],
      invalidCombinations: [
        'src without alt',
        'status indicator without accessible label',
      ],
    },
    responsiveBehavior: ['fixed size; use size prop for responsive variants'],
    styleHooks: ['avatar.bg', 'avatar.color', 'avatar.border', 'avatar.radius'],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: false,
    },
    recipes: [
      {
        id: 'user-avatar-with-name',
        label: 'Avatar with Name',
        description: 'Avatar alongside display name and secondary label.',
        requiredProps: ['alt'],
        recommendedDefaults: { size: 'md', shape: 'circle' },
      },
    ],
    antiPatterns: [
      {
        id: 'avatar-no-alt',
        description: 'Avatar image without alt attribute.',
        reason:
          'Image is invisible to screen readers; user identity is not communicated.',
        fix: 'Always provide alt with the person\'s name or alt="" for purely decorative avatars.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'icon',
    slug: 'icon',
    displayName: 'Icon',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'media',
    description:
      'Wrapper for SVG icon primitives from the design system icon set.',
    status: 'stable',
    tags: ['icon', 'svg', 'visual'],
    props: [
      {
        name: 'name',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        required: true,
        description: 'Icon identifier from the icon set.',
      },
      commonSizeProp,
      commonToneProp,
      commonClassNameProp,
      commonLabelProp,
      {
        name: 'decorative',
        type: 'boolean',
        category: 'accessibility',
        editingSurface: 'advanced-edit',
        description:
          'When true, the icon is hidden from assistive technology (aria-hidden).',
        defaultValue: 'false',
      },
    ],
    slots: [],
    events: [],
    states: ['default'],
    a11y: {
      role: 'img',
      ariaRequired: ['aria-label when decorative=false'],
      keyboard: [],
      focusBehavior: 'Non-interactive; not focusable.',
      screenReaderNotes: [
        'Standalone meaningful icons require aria-label or label prop.',
        'Icons inside labelled buttons should use decorative=true.',
        'Never convey information through icon shape alone without a text alternative.',
      ],
      invalidCombinations: ['decorative=false without label or aria-label'],
    },
    responsiveBehavior: ['fixed size; scales with size prop'],
    styleHooks: ['icon.color', 'icon.size'],
    builder: {
      editingSurface: 'prop-driven',
      allowChildren: false,
    },
    recipes: [],
    antiPatterns: [
      {
        id: 'icon-only-no-accessible-name',
        description: 'Meaningful icon without accessible name.',
        reason: 'Icon purpose is invisible to screen readers.',
        fix: 'Set decorative=false and provide label, or ensure parent element carries the label.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
];
