import {
  baseCompatibility,
  commonChildrenProp,
  commonClassNameProp,
  commonIconProp,
  commonSizeProp,
  commonToneProp,
  commonVariantProp,
  interactiveRule,
  type RegistryComponent,
} from './shared';

export const navigationComponents: RegistryComponent[] = [
  {
    id: 'link',
    slug: 'link',
    displayName: 'Link',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'navigation',
    description: 'Navigation text link. Renders as <a> by default.',
    status: 'stable',
    tags: ['navigation', 'interactive'],
    props: [
      {
        name: 'href',
        type: 'string',
        category: 'content',
        editingSurface: 'content-edit',
        required: true,
        description: 'Link destination URL.',
      },
      {
        name: 'target',
        type: 'string',
        category: 'behavior',
        editingSurface: 'advanced-edit',
        description: 'Browsing context (_blank | _self | _parent | _top).',
        defaultValue: '_self',
      },
      {
        name: 'rel',
        type: 'string',
        category: 'accessibility',
        editingSurface: 'advanced-edit',
        description:
          'Link relationship. Defaults to "noopener noreferrer" when target="_blank".',
      },
      commonVariantProp,
      commonSizeProp,
      commonToneProp,
      commonClassNameProp,
      commonChildrenProp,
      commonIconProp,
      {
        name: 'onClick',
        type: '(event: React.MouseEvent) => void',
        category: 'behavior',
        editingSurface: 'hidden',
        semantics: 'computed',
        description: 'Click handler.',
      },
    ],
    slots: ['default'],
    events: ['onClick'],
    states: ['default', 'hover', 'focus', 'visited', 'active'],
    a11y: {
      role: 'link',
      ariaRequired: [],
      keyboard: ['Enter'],
      focusBehavior: 'Focusable via Tab. Activates on Enter.',
      screenReaderNotes: [
        'Link text must be meaningful out of context.',
        'External links (target="_blank") should announce opening in new tab via visually-hidden text or aria-label.',
      ],
      invalidCombinations: [
        'empty or whitespace-only href',
        'onClick without href for navigation (use Button instead)',
      ],
      localizationNotes: [
        'Avoid directional language ("click here", "see above") in link text.',
      ],
    },
    responsiveBehavior: [
      'inline wrapping',
      'touch target padding applies at mobile viewports',
    ],
    styleHooks: ['link.color', 'link.decoration', 'link.visited.color'],
    builder: {
      editingSurface: 'inline-editable',
      allowChildren: true,
      insertionRules: interactiveRule,
    },
    recipes: [
      {
        id: 'sidebar-nav-link',
        label: 'Sidebar Navigation Link',
        description: 'Link inside a sidebar nav group with icon and label.',
        requiredProps: ['href', 'children'],
        recommendedDefaults: { variant: 'ghost', tone: 'neutral' },
        doExample:
          '<Link href="/dashboard" icon={<DashboardIcon />}>Dashboard</Link>',
        dontExample: '<Link href="/dashboard">Click here</Link>',
      },
    ],
    antiPatterns: [
      {
        id: 'empty-href',
        description: 'Link with empty, "#", or "javascript:void(0)" href.',
        reason:
          'Not a real navigation target; breaks keyboard and assistive technology behaviour.',
        fix: 'Use Button with onClick for non-navigation actions.',
      },
      {
        id: 'generic-link-text',
        description:
          'Link text is "click here", "read more", or similarly non-descriptive.',
        reason:
          'Screen reader users navigating by links cannot determine the destination.',
        fix: 'Describe the destination or action in the link text.',
      },
    ],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'breadcrumb',
    slug: 'breadcrumb',
    displayName: 'Breadcrumb',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'navigation',
    description: 'Navigation trail for hierarchical pages.',
    status: 'stable',
    tags: ['navigation', 'trail'],
    props: [commonChildrenProp, commonClassNameProp],
    slots: ['default'],
    events: [],
    states: ['default'],
    a11y: {
      role: 'navigation',
      keyboard: ['Tab'],
      focusBehavior: 'Links and buttons within the trail are focusable.',
      screenReaderNotes: [
        'Wrap in a nav landmark with aria-label="Breadcrumb".',
      ],
    },
    responsiveBehavior: ['wrap'],
    styleHooks: ['breadcrumb.color'],
    builder: { editingSurface: 'layout-container', allowChildren: true },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'command-palette',
    slug: 'command-palette',
    displayName: 'CommandPalette',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'navigation',
    description: 'Keyboard-driven command palette overlay.',
    status: 'stable',
    tags: ['overlay', 'commands'],
    props: [commonClassNameProp],
    slots: ['input', 'listbox'],
    events: ['onOpenChange'],
    states: ['closed', 'open', 'filtering'],
    a11y: {
      role: 'dialog',
      keyboard: ['ArrowDown', 'ArrowUp', 'Enter', 'Escape'],
      focusBehavior: 'Focus moves to search input when opened.',
      screenReaderNotes: [
        'Use dialog semantics and expose results as options.',
      ],
    },
    responsiveBehavior: ['overlay'],
    styleHooks: ['command-palette.bg'],
    builder: { editingSurface: 'overlay', allowChildren: true },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
  {
    id: 'drawer',
    slug: 'drawer',
    displayName: 'Drawer',
    package: '@ui-construction-library/core',
    version: '0.1.0',
    category: 'navigation',
    description: 'Side sheet panel overlay.',
    status: 'stable',
    tags: ['overlay', 'panel'],
    props: [commonClassNameProp],
    slots: ['default'],
    events: ['onOpenChange'],
    states: ['closed', 'open'],
    a11y: {
      role: 'dialog',
      keyboard: ['Escape'],
      focusBehavior: 'Focus trapped while open.',
      screenReaderNotes: [
        'Provide title and description when content is not obvious.',
      ],
    },
    responsiveBehavior: ['overlay'],
    styleHooks: ['drawer.bg'],
    builder: { editingSurface: 'overlay', allowChildren: true },
    recipes: [],
    antiPatterns: [],
    export: { react: 'supported', next: 'supported' },
    compatibility: baseCompatibility,
  },
];
