#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..', '..');
const presetsPath = path.join(root, 'registry', 'source', 'presets.json');

function exitWith(message) {
  console.error(`[preset-bootstrap] ${message}`);
  process.exit(1);
}

if (!fs.existsSync(presetsPath)) {
  exitWith(`Presets file not found: ${presetsPath}`);
}

const presetName = process.argv[2];
if (!presetName) {
  exitWith(
    'Usage: node scripts/utils/bootstrap-preset.js <enterprise|saas|marketing>'
  );
}

const registry = JSON.parse(fs.readFileSync(presetsPath, 'utf8'));
const preset = registry.presets?.[presetName];

if (!preset) {
  exitWith(
    `Unknown preset "${presetName}". Available: ${Object.keys(registry.presets || {}).join(', ')}`
  );
}

const lines = [];
lines.push('# Generated by scripts/utils/bootstrap-preset.js');
lines.push(`preset: ${presetName}`);
lines.push(`description: ${preset.description}`);
lines.push('');
lines.push('## Dependencies');
for (const dep of preset.dependencies) {
  lines.push(`- ${dep}`);
}
lines.push('');
lines.push('## Features');
for (const feature of preset.features) {
  lines.push(`- ${feature}`);
}
lines.push('');
lines.push('## Install');
lines.push(`pnpm add ${preset.dependencies.join(' ')}`);

const outputPath = path.join(root, 'docs', 'guides', `preset-${presetName}.md`);
fs.writeFileSync(outputPath, `${lines.join('\n')}\n`, 'utf8');

console.log(`[preset-bootstrap] Generated ${path.relative(root, outputPath)}`);
console.log(
  `[preset-bootstrap] Install command: pnpm add ${preset.dependencies.join(' ')}`
);
