export type IconCategory =
  | 'navigation-direction'
  | 'actions-editing'
  | 'status-feedback'
  | 'users-auth'
  | 'files-content'
  | 'data-layout'
  | 'commerce-finance'
  | 'media-devices'
  | 'development-brands'
  | 'toggles-visibility';

export type IconManifestEntry = {
  componentName: string;
  exportName: string;
  name: string;
  aliases?: string[];
  keywords: string[];
  category: IconCategory;
  status: 'ready' | 'planned';
};

export const iconManifest = [
  {
    componentName: 'FocusIcon',
    exportName: 'FocusIcon',
    name: 'focus',
    keywords: ['focus', 'target', 'scan', 'frame'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'EyeOffIcon',
    exportName: 'EyeOffIcon',
    name: 'eye-off',
    keywords: ['eye', 'off', 'hidden', 'privacy'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'EyeIcon',
    exportName: 'EyeIcon',
    name: 'eye',
    keywords: ['eye', 'view', 'visibility', 'show'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'HomeIcon',
    exportName: 'HomeIcon',
    name: 'home',
    keywords: ['home', 'house', 'dashboard', 'main'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'BookmarkPlusIcon',
    exportName: 'BookmarkPlusIcon',
    name: 'bookmark-plus',
    keywords: ['bookmark', 'plus', 'save', 'add'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FolderGitIcon',
    exportName: 'FolderGitIcon',
    name: 'folder-git',
    keywords: ['folder', 'git', 'repository', 'source'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'RedoIcon',
    exportName: 'RedoIcon',
    name: 'redo',
    keywords: ['redo', 'arrow', 'history', 'forward'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'UndoIcon',
    exportName: 'UndoIcon',
    name: 'undo',
    keywords: ['undo', 'arrow', 'history', 'back'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'UnlinkIcon',
    exportName: 'UnlinkIcon',
    name: 'unlink',
    keywords: ['unlink', 'disconnect', 'chain', 'broken'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'LinkIcon',
    exportName: 'LinkIcon',
    name: 'link',
    keywords: ['link', 'chain', 'connect', 'url'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ExternalLinkIcon',
    exportName: 'ExternalLinkIcon',
    name: 'external-link',
    keywords: ['external', 'link', 'open', 'new-tab'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'MoveRightIcon',
    exportName: 'MoveRightIcon',
    name: 'move-right',
    keywords: ['move', 'right', 'arrow', 'direction'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'MoveLeftIcon',
    exportName: 'MoveLeftIcon',
    name: 'move-left',
    keywords: ['move', 'left', 'arrow', 'direction'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'MoveDownIcon',
    exportName: 'MoveDownIcon',
    name: 'move-down',
    keywords: ['move', 'down', 'arrow', 'direction'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'MoveUpIcon',
    exportName: 'MoveUpIcon',
    name: 'move-up',
    keywords: ['move', 'up', 'arrow', 'direction'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'CornerDownRightIcon',
    exportName: 'CornerDownRightIcon',
    name: 'corner-down-right',
    keywords: ['corner', 'down', 'right', 'arrow'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'CornerDownLeftIcon',
    exportName: 'CornerDownLeftIcon',
    name: 'corner-down-left',
    keywords: ['corner', 'down', 'left', 'arrow'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'CornerUpRightIcon',
    exportName: 'CornerUpRightIcon',
    name: 'corner-up-right',
    keywords: ['corner', 'up', 'right', 'arrow'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'CornerUpLeftIcon',
    exportName: 'CornerUpLeftIcon',
    name: 'corner-up-left',
    keywords: ['corner', 'up', 'left', 'arrow'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'LogOutIcon',
    exportName: 'LogOutIcon',
    name: 'log-out',
    keywords: ['logout', 'sign out', 'exit', 'auth'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'LogInIcon',
    exportName: 'LogInIcon',
    name: 'log-in',
    keywords: ['login', 'sign in', 'enter', 'auth'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'FingerprintIcon',
    exportName: 'FingerprintIcon',
    name: 'fingerprint',
    keywords: ['fingerprint', 'biometric', 'security', 'auth'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'KeyIcon',
    exportName: 'KeyIcon',
    name: 'key',
    keywords: ['key', 'security', 'password', 'auth'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UnlockIcon',
    exportName: 'UnlockIcon',
    name: 'unlock',
    keywords: ['unlock', 'security', 'access', 'auth'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'LockIcon',
    exportName: 'LockIcon',
    name: 'lock',
    keywords: ['lock', 'security', 'private', 'auth'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'CameraOffIcon',
    exportName: 'CameraOffIcon',
    name: 'camera-off',
    keywords: ['camera', 'off', 'privacy', 'media'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'CameraIcon',
    exportName: 'CameraIcon',
    name: 'camera',
    keywords: ['camera', 'photo', 'image', 'media'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'MicOffIcon',
    exportName: 'MicOffIcon',
    name: 'mic-off',
    keywords: ['mic', 'mute', 'audio', 'voice'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'MicIcon',
    exportName: 'MicIcon',
    name: 'mic',
    keywords: ['mic', 'audio', 'voice', 'record'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'VideoIcon',
    exportName: 'VideoIcon',
    name: 'video',
    keywords: ['video', 'call', 'camera', 'meeting'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'PhoneOffIcon',
    exportName: 'PhoneOffIcon',
    name: 'phone-off',
    keywords: ['phone', 'off', 'mute', 'call'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'PhoneCallIcon',
    exportName: 'PhoneCallIcon',
    name: 'phone-call',
    keywords: ['phone', 'call', 'ring', 'contact'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'PhoneIcon',
    exportName: 'PhoneIcon',
    name: 'phone',
    keywords: ['phone', 'call', 'contact', 'device'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'MessagesSquareIcon',
    exportName: 'MessagesSquareIcon',
    name: 'messages-square',
    keywords: ['messages', 'chat', 'conversation', 'thread'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'MessageSquareIcon',
    exportName: 'MessageSquareIcon',
    name: 'message-square',
    keywords: ['message', 'chat', 'comment', 'bubble'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'MessageCircleIcon',
    exportName: 'MessageCircleIcon',
    name: 'message-circle',
    keywords: ['message', 'chat', 'comment', 'bubble'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'InboxIcon',
    exportName: 'InboxIcon',
    name: 'inbox',
    keywords: ['inbox', 'mail', 'message', 'tray'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'MailIcon',
    exportName: 'MailIcon',
    name: 'mail',
    keywords: ['mail', 'email', 'message', 'inbox'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'AtSignIcon',
    exportName: 'AtSignIcon',
    name: 'at-sign',
    keywords: ['at', 'mention', 'handle', 'email'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'ContactIcon',
    exportName: 'ContactIcon',
    name: 'contact',
    keywords: ['contact', 'profile', 'address', 'person'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UserSquareIcon',
    exportName: 'UserSquareIcon',
    name: 'user-square',
    keywords: ['user', 'square', 'profile', 'avatar'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UserCircleIcon',
    exportName: 'UserCircleIcon',
    name: 'user-circle',
    keywords: ['user', 'circle', 'profile', 'avatar'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UserXIcon',
    exportName: 'UserXIcon',
    name: 'user-x',
    keywords: ['user', 'x', 'blocked', 'remove'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UserCheckIcon',
    exportName: 'UserCheckIcon',
    name: 'user-check',
    keywords: ['user', 'check', 'verified', 'member'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UserMinusIcon',
    exportName: 'UserMinusIcon',
    name: 'user-minus',
    keywords: ['user', 'minus', 'remove', 'member'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UserPlusIcon',
    exportName: 'UserPlusIcon',
    name: 'user-plus',
    keywords: ['user', 'plus', 'invite', 'add'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UsersIcon',
    exportName: 'UsersIcon',
    name: 'users',
    keywords: ['users', 'group', 'team', 'people'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'UserIcon',
    exportName: 'UserIcon',
    name: 'user',
    keywords: ['user', 'person', 'account', 'profile'],
    category: 'users-auth',
    status: 'ready',
  },
  {
    componentName: 'ThumbsDownIcon',
    exportName: 'ThumbsDownIcon',
    name: 'thumbs-down',
    keywords: ['thumbs', 'down', 'dislike', 'reject'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'ThumbsUpIcon',
    exportName: 'ThumbsUpIcon',
    name: 'thumbs-up',
    keywords: ['thumbs', 'up', 'like', 'approve'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'HeartOffIcon',
    exportName: 'HeartOffIcon',
    name: 'heart-off',
    keywords: ['heart', 'off', 'unlike', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'HeartIcon',
    exportName: 'HeartIcon',
    name: 'heart',
    keywords: ['heart', 'like', 'favorite', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'StarOffIcon',
    exportName: 'StarOffIcon',
    name: 'star-off',
    keywords: ['star', 'off', 'favorite', 'remove'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'StarIcon',
    exportName: 'StarIcon',
    name: 'star',
    keywords: ['star', 'favorite', 'rating', 'save'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'FlagOffIcon',
    exportName: 'FlagOffIcon',
    name: 'flag-off',
    keywords: ['flag', 'off', 'unmark', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'FlagIcon',
    exportName: 'FlagIcon',
    name: 'flag',
    keywords: ['flag', 'mark', 'important', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'PulseIcon',
    exportName: 'PulseIcon',
    name: 'pulse',
    keywords: ['pulse', 'health', 'activity', 'signal'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'ActivityIcon',
    exportName: 'ActivityIcon',
    name: 'activity',
    keywords: ['activity', 'pulse', 'health', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'NotificationIcon',
    exportName: 'NotificationIcon',
    name: 'notification',
    keywords: ['notification', 'alert', 'status', 'feed'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'BellOffIcon',
    exportName: 'BellOffIcon',
    name: 'bell-off',
    keywords: ['bell', 'off', 'mute', 'notification'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'BellIcon',
    exportName: 'BellIcon',
    name: 'bell',
    keywords: ['bell', 'notification', 'alert', 'reminder'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'CalendarDaysIcon',
    exportName: 'CalendarDaysIcon',
    name: 'calendar-days',
    keywords: ['calendar', 'days', 'date', 'schedule'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'CalendarIcon',
    exportName: 'CalendarIcon',
    name: 'calendar',
    keywords: ['calendar', 'date', 'schedule', 'event'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'HistoryIcon',
    exportName: 'HistoryIcon',
    name: 'history',
    keywords: ['history', 'recent', 'time', 'log'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'ClockIcon',
    exportName: 'ClockIcon',
    name: 'clock',
    keywords: ['clock', 'time', 'schedule', 'history'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'LoaderCircleIcon',
    exportName: 'LoaderCircleIcon',
    name: 'loader-circle',
    keywords: ['loader', 'spinner', 'circle', 'progress'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'LoaderIcon',
    exportName: 'LoaderIcon',
    name: 'loader',
    keywords: ['loader', 'spinner', 'progress', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'BanIcon',
    exportName: 'BanIcon',
    name: 'ban',
    keywords: ['ban', 'blocked', 'forbidden', 'disabled'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'ShieldXIcon',
    exportName: 'ShieldXIcon',
    name: 'shield-x',
    keywords: ['shield', 'x', 'security', 'blocked'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'ShieldCheckIcon',
    exportName: 'ShieldCheckIcon',
    name: 'shield-check',
    keywords: ['shield', 'check', 'security', 'safe'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'ShieldAlertIcon',
    exportName: 'ShieldAlertIcon',
    name: 'shield-alert',
    keywords: ['shield', 'alert', 'security', 'warning'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'AlertCircleIcon',
    exportName: 'AlertCircleIcon',
    name: 'alert-circle',
    keywords: ['alert', 'warning', 'circle', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'AlertTriangleIcon',
    exportName: 'AlertTriangleIcon',
    name: 'alert-triangle',
    keywords: ['alert', 'warning', 'triangle', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'HelpCircleIcon',
    exportName: 'HelpCircleIcon',
    name: 'help-circle',
    keywords: ['help', 'question', 'support', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'InfoIcon',
    exportName: 'InfoIcon',
    name: 'info',
    keywords: ['info', 'information', 'details', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'SearchIcon',
    exportName: 'SearchIcon',
    name: 'search',
    keywords: ['search', 'find', 'magnifier', 'lookup'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'SettingsIcon',
    exportName: 'SettingsIcon',
    name: 'settings',
    keywords: ['settings', 'gear', 'preferences', 'config'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'RefreshCcwIcon',
    exportName: 'RefreshCcwIcon',
    name: 'refresh-ccw',
    keywords: ['refresh', 'reload', 'sync', 'counterclockwise'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'RefreshCwIcon',
    exportName: 'RefreshCwIcon',
    name: 'refresh-cw',
    keywords: ['refresh', 'reload', 'sync', 'clockwise'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ForwardIcon',
    exportName: 'ForwardIcon',
    name: 'forward',
    keywords: ['forward', 'share', 'message', 'mail'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ReplyIcon',
    exportName: 'ReplyIcon',
    name: 'reply',
    keywords: ['reply', 'response', 'message', 'mail'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'SendIcon',
    exportName: 'SendIcon',
    name: 'send',
    keywords: ['send', 'submit', 'message', 'paper-plane'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ShareIcon',
    exportName: 'ShareIcon',
    name: 'share',
    keywords: ['share', 'send', 'external', 'publish'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ExportIcon',
    exportName: 'ExportIcon',
    name: 'export',
    keywords: ['export', 'outbound', 'arrow', 'data'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ImportIcon',
    exportName: 'ImportIcon',
    name: 'import',
    keywords: ['import', 'inbound', 'arrow', 'data'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'UploadIcon',
    exportName: 'UploadIcon',
    name: 'upload',
    keywords: ['upload', 'arrow', 'export', 'file'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'DownloadIcon',
    exportName: 'DownloadIcon',
    name: 'download',
    keywords: ['download', 'arrow', 'import', 'file'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'SaveIcon',
    exportName: 'SaveIcon',
    name: 'save',
    keywords: ['save', 'persist', 'disk', 'storage'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ScissorsIcon',
    exportName: 'ScissorsIcon',
    name: 'scissors',
    keywords: ['scissors', 'cut', 'trim', 'edit'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ClipboardCheckIcon',
    exportName: 'ClipboardCheckIcon',
    name: 'clipboard-check',
    keywords: ['clipboard', 'check', 'copied', 'done'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ClipboardIcon',
    exportName: 'ClipboardIcon',
    name: 'clipboard',
    keywords: ['clipboard', 'paste', 'copy', 'notes'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'CopyIcon',
    exportName: 'CopyIcon',
    name: 'copy',
    keywords: ['copy', 'duplicate', 'clone', 'clipboard'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'TrashIcon',
    exportName: 'TrashIcon',
    name: 'trash',
    keywords: ['trash', 'delete', 'remove', 'bin'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'PencilIcon',
    exportName: 'PencilIcon',
    name: 'pencil',
    keywords: ['pencil', 'edit', 'write', 'draft'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'EditIcon',
    exportName: 'EditIcon',
    name: 'edit',
    keywords: ['edit', 'modify', 'write', 'change'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'XCircleIcon',
    exportName: 'XCircleIcon',
    name: 'x-circle',
    keywords: ['x', 'circle', 'error', 'close'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'CheckCircleIcon',
    exportName: 'CheckCircleIcon',
    name: 'check-circle',
    keywords: ['check', 'circle', 'confirm', 'done'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'CheckIcon',
    exportName: 'CheckIcon',
    name: 'check',
    keywords: ['check', 'confirm', 'done', 'success'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'XIcon',
    exportName: 'XIcon',
    name: 'x',
    keywords: ['x', 'close', 'cancel', 'dismiss'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'MinusIcon',
    exportName: 'MinusIcon',
    name: 'minus',
    keywords: ['minus', 'remove', 'subtract', 'delete'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'PlusIcon',
    exportName: 'PlusIcon',
    name: 'plus',
    keywords: ['plus', 'add', 'create', 'new'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'MenuIcon',
    exportName: 'MenuIcon',
    name: 'menu',
    keywords: ['menu', 'navigation', 'hamburger', 'sidebar'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'MoreVerticalIcon',
    exportName: 'MoreVerticalIcon',
    name: 'more-vertical',
    keywords: ['more', 'menu', 'vertical', 'overflow'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'MoreHorizontalIcon',
    exportName: 'MoreHorizontalIcon',
    name: 'more-horizontal',
    keywords: ['more', 'menu', 'horizontal', 'overflow'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ChevronRightIcon',
    exportName: 'ChevronRightIcon',
    name: 'chevron-right',
    keywords: ['chevron', 'right', 'direction', 'navigation'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ChevronLeftIcon',
    exportName: 'ChevronLeftIcon',
    name: 'chevron-left',
    keywords: ['chevron', 'left', 'direction', 'navigation'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ChevronDownIcon',
    exportName: 'ChevronDownIcon',
    name: 'chevron-down',
    keywords: ['chevron', 'down', 'direction', 'navigation'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ChevronUpIcon',
    exportName: 'ChevronUpIcon',
    name: 'chevron-up',
    keywords: ['chevron', 'up', 'direction', 'navigation'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ArrowRightIcon',
    exportName: 'ArrowRightIcon',
    name: 'arrow-right',
    keywords: ['arrow', 'right', 'direction', 'navigation'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ArrowLeftIcon',
    exportName: 'ArrowLeftIcon',
    name: 'arrow-left',
    keywords: ['arrow', 'left', 'direction', 'navigation'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ArrowDownIcon',
    exportName: 'ArrowDownIcon',
    name: 'arrow-down',
    keywords: ['arrow', 'down', 'direction', 'navigation'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ArrowUpIcon',
    exportName: 'ArrowUpIcon',
    name: 'arrow-up',
    keywords: ['arrow', 'up', 'direction', 'navigation'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'MoonIcon',
    exportName: 'MoonIcon',
    name: 'moon',
    keywords: ['moon', 'theme', 'dark', 'appearance'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'SunIcon',
    exportName: 'SunIcon',
    name: 'sun',
    keywords: ['sun', 'theme', 'light', 'appearance'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'MonitorCogIcon',
    exportName: 'MonitorCogIcon',
    name: 'monitor-cog',
    keywords: ['monitor', 'settings', 'display', 'appearance'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'ContrastIcon',
    exportName: 'ContrastIcon',
    name: 'contrast',
    keywords: ['contrast', 'theme', 'appearance', 'mode'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'AccessibilityIcon',
    exportName: 'AccessibilityIcon',
    name: 'accessibility',
    keywords: ['accessibility', 'a11y', 'inclusive', 'settings'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'MaximizeIcon',
    exportName: 'MaximizeIcon',
    name: 'maximize',
    keywords: ['maximize', 'expand', 'fullscreen', 'ui'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'MinimizeIcon',
    exportName: 'MinimizeIcon',
    name: 'minimize',
    keywords: ['minimize', 'collapse', 'ui', 'window'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'PinIcon',
    exportName: 'PinIcon',
    name: 'pin',
    keywords: ['pin', 'save', 'anchor', 'state'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'PinOffIcon',
    exportName: 'PinOffIcon',
    name: 'pin-off',
    keywords: ['pin', 'off', 'unpin', 'state'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'BookmarkCheckIcon',
    exportName: 'BookmarkCheckIcon',
    name: 'bookmark-check',
    keywords: ['bookmark', 'check', 'save', 'done'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'BookmarkXIcon',
    exportName: 'BookmarkXIcon',
    name: 'bookmark-x',
    keywords: ['bookmark', 'x', 'remove', 'save'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'ToggleLeftIcon',
    exportName: 'ToggleLeftIcon',
    name: 'toggle-left',
    keywords: ['toggle', 'left', 'switch', 'off'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'ToggleRightIcon',
    exportName: 'ToggleRightIcon',
    name: 'toggle-right',
    keywords: ['toggle', 'right', 'switch', 'on'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'CheckSquareIcon',
    exportName: 'CheckSquareIcon',
    name: 'check-square',
    keywords: ['check', 'square', 'checkbox', 'done'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'SquareIcon',
    exportName: 'SquareIcon',
    name: 'square',
    keywords: ['square', 'shape', 'checkbox', 'empty'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'SquareDashedIcon',
    exportName: 'SquareDashedIcon',
    name: 'square-dashed',
    keywords: ['square', 'dashed', 'selection', 'shape'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'CircleIcon',
    exportName: 'CircleIcon',
    name: 'circle',
    keywords: ['circle', 'shape', 'radio', 'empty'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'DotIcon',
    exportName: 'DotIcon',
    name: 'dot',
    keywords: ['dot', 'point', 'bullet', 'shape'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'RadioIcon',
    exportName: 'RadioIcon',
    name: 'radio',
    keywords: ['radio', 'select', 'choice', 'input'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'ScanIcon',
    exportName: 'ScanIcon',
    name: 'scan',
    keywords: ['scan', 'detect', 'frame', 'focus'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'QrCodeIcon',
    exportName: 'QrCodeIcon',
    name: 'qr-code',
    keywords: ['qr', 'code', 'scan', 'auth'],
    category: 'toggles-visibility',
    status: 'ready',
  },
  {
    componentName: 'ShieldIcon',
    exportName: 'ShieldIcon',
    name: 'shield',
    keywords: ['shield', 'security', 'protect', 'safe'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'AlertOctagonIcon',
    exportName: 'AlertOctagonIcon',
    name: 'alert-octagon',
    keywords: ['alert', 'octagon', 'danger', 'warning'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'CircleCheckIcon',
    exportName: 'CircleCheckIcon',
    name: 'circle-check',
    keywords: ['check', 'circle', 'success', 'done'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'CircleXIcon',
    exportName: 'CircleXIcon',
    name: 'circle-x',
    keywords: ['x', 'circle', 'error', 'close'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'CircleAlertIcon',
    exportName: 'CircleAlertIcon',
    name: 'circle-alert',
    keywords: ['alert', 'circle', 'warning', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'CircleHelpIcon',
    exportName: 'CircleHelpIcon',
    name: 'circle-help',
    keywords: ['help', 'circle', 'support', 'question'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'Loader2Icon',
    exportName: 'Loader2Icon',
    name: 'loader-2',
    keywords: ['loader', 'spinner', 'progress', 'status'],
    category: 'status-feedback',
    status: 'ready',
  },
  {
    componentName: 'SparkleIcon',
    exportName: 'SparkleIcon',
    name: 'sparkle',
    keywords: ['sparkle', 'magic', 'accent', 'status'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'CodeIcon',
    exportName: 'CodeIcon',
    name: 'code',
    keywords: ['code', 'dev', 'programming', 'markup'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'Code2Icon',
    exportName: 'Code2Icon',
    name: 'code-2',
    keywords: ['code', 'dev', 'programming', 'syntax'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'TerminalIcon',
    exportName: 'TerminalIcon',
    name: 'terminal',
    keywords: ['terminal', 'console', 'shell', 'dev'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'CommandIcon',
    exportName: 'CommandIcon',
    name: 'command',
    keywords: ['command', 'keyboard', 'shortcut', 'dev'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'BracesIcon',
    exportName: 'BracesIcon',
    name: 'braces',
    keywords: ['braces', 'syntax', 'code', 'json'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'BracketsIcon',
    exportName: 'BracketsIcon',
    name: 'brackets',
    keywords: ['brackets', 'syntax', 'code', 'array'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'BugIcon',
    exportName: 'BugIcon',
    name: 'bug',
    keywords: ['bug', 'debug', 'issue', 'dev'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'TestTubeIcon',
    exportName: 'TestTubeIcon',
    name: 'test-tube',
    keywords: ['test', 'tube', 'qa', 'experiment'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'GitBranchIcon',
    exportName: 'GitBranchIcon',
    name: 'git-branch',
    keywords: ['git', 'branch', 'version', 'dev'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'GitCommitIcon',
    exportName: 'GitCommitIcon',
    name: 'git-commit',
    keywords: ['git', 'commit', 'version', 'dev'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'GitPullRequestIcon',
    exportName: 'GitPullRequestIcon',
    name: 'git-pull-request',
    keywords: ['git', 'pull request', 'merge', 'dev'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'GithubIcon',
    exportName: 'GithubIcon',
    name: 'github',
    keywords: ['github', 'git', 'repo', 'brand'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'GitlabIcon',
    exportName: 'GitlabIcon',
    name: 'gitlab',
    keywords: ['gitlab', 'git', 'repo', 'brand'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'NpmIcon',
    exportName: 'NpmIcon',
    name: 'npm',
    keywords: ['npm', 'package', 'registry', 'brand'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'PackageSearchIcon',
    exportName: 'PackageSearchIcon',
    name: 'package-search',
    keywords: ['package', 'search', 'registry', 'dev'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'BlocksIcon',
    exportName: 'BlocksIcon',
    name: 'blocks',
    keywords: ['blocks', 'builder', 'ui', 'component'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'ComponentIcon',
    exportName: 'ComponentIcon',
    name: 'component',
    keywords: ['component', 'ui', 'library', 'design system'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'PaletteIcon',
    exportName: 'PaletteIcon',
    name: 'palette',
    keywords: ['palette', 'design', 'color', 'brand'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'PaintBucketIcon',
    exportName: 'PaintBucketIcon',
    name: 'paint-bucket',
    keywords: ['paint', 'bucket', 'fill', 'design'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'PenToolIcon',
    exportName: 'PenToolIcon',
    name: 'pen-tool',
    keywords: ['pen', 'tool', 'design', 'vector'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'FigmaIcon',
    exportName: 'FigmaIcon',
    name: 'figma',
    keywords: ['figma', 'design', 'brand', 'ui'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'ChromeIcon',
    exportName: 'ChromeIcon',
    name: 'chrome',
    keywords: ['chrome', 'browser', 'brand', 'web'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'SafariIcon',
    exportName: 'SafariIcon',
    name: 'safari',
    keywords: ['safari', 'browser', 'brand', 'web'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'CloudIcon',
    exportName: 'CloudIcon',
    name: 'cloud',
    keywords: ['cloud', 'infra', 'storage', 'service'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'CloudOffIcon',
    exportName: 'CloudOffIcon',
    name: 'cloud-off',
    keywords: ['cloud', 'off', 'infra', 'offline'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'CloudUploadIcon',
    exportName: 'CloudUploadIcon',
    name: 'cloud-upload',
    keywords: ['cloud', 'upload', 'infra', 'storage'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'CloudDownloadIcon',
    exportName: 'CloudDownloadIcon',
    name: 'cloud-download',
    keywords: ['cloud', 'download', 'infra', 'storage'],
    category: 'development-brands',
    status: 'ready',
  },
  {
    componentName: 'PlayIcon',
    exportName: 'PlayIcon',
    name: 'play',
    keywords: ['play', 'media', 'start', 'video'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'PauseIcon',
    exportName: 'PauseIcon',
    name: 'pause',
    keywords: ['pause', 'media', 'video', 'audio'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'PlayCircleIcon',
    exportName: 'PlayCircleIcon',
    name: 'play-circle',
    keywords: ['play', 'circle', 'media', 'video'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'StopCircleIcon',
    exportName: 'StopCircleIcon',
    name: 'stop-circle',
    keywords: ['stop', 'circle', 'media', 'video'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'SkipBackIcon',
    exportName: 'SkipBackIcon',
    name: 'skip-back',
    keywords: ['skip', 'back', 'media', 'audio'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'SkipForwardIcon',
    exportName: 'SkipForwardIcon',
    name: 'skip-forward',
    keywords: ['skip', 'forward', 'media', 'audio'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'RewindIcon',
    exportName: 'RewindIcon',
    name: 'rewind',
    keywords: ['rewind', 'media', 'audio', 'video'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'FastForwardIcon',
    exportName: 'FastForwardIcon',
    name: 'fast-forward',
    keywords: ['fast', 'forward', 'media', 'video'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'VolumeIcon',
    exportName: 'VolumeIcon',
    name: 'volume',
    keywords: ['volume', 'audio', 'speaker', 'media'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'Volume1Icon',
    exportName: 'Volume1Icon',
    name: 'volume-1',
    keywords: ['volume', 'audio', 'low', 'speaker'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'Volume2Icon',
    exportName: 'Volume2Icon',
    name: 'volume-2',
    keywords: ['volume', 'audio', 'high', 'speaker'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'VolumeXIcon',
    exportName: 'VolumeXIcon',
    name: 'volume-x',
    keywords: ['volume', 'mute', 'audio', 'speaker'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'HeadphonesIcon',
    exportName: 'HeadphonesIcon',
    name: 'headphones',
    keywords: ['headphones', 'audio', 'music', 'device'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'SpeakerIcon',
    exportName: 'SpeakerIcon',
    name: 'speaker',
    keywords: ['speaker', 'audio', 'device', 'music'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'MonitorIcon',
    exportName: 'MonitorIcon',
    name: 'monitor',
    keywords: ['monitor', 'display', 'desktop', 'device'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'LaptopIcon',
    exportName: 'LaptopIcon',
    name: 'laptop',
    keywords: ['laptop', 'computer', 'device', 'desktop'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'TabletIcon',
    exportName: 'TabletIcon',
    name: 'tablet',
    keywords: ['tablet', 'device', 'mobile', 'screen'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'SmartphoneIcon',
    exportName: 'SmartphoneIcon',
    name: 'smartphone',
    keywords: ['smartphone', 'phone', 'device', 'mobile'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'WatchIcon',
    exportName: 'WatchIcon',
    name: 'watch',
    keywords: ['watch', 'wearable', 'device', 'time'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'TvIcon',
    exportName: 'TvIcon',
    name: 'tv',
    keywords: ['tv', 'screen', 'media', 'device'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'CastIcon',
    exportName: 'CastIcon',
    name: 'cast',
    keywords: ['cast', 'screen', 'stream', 'device'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'BluetoothIcon',
    exportName: 'BluetoothIcon',
    name: 'bluetooth',
    keywords: ['bluetooth', 'wireless', 'device', 'connection'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'WifiIcon',
    exportName: 'WifiIcon',
    name: 'wifi',
    keywords: ['wifi', 'wireless', 'network', 'connection'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'WifiOffIcon',
    exportName: 'WifiOffIcon',
    name: 'wifi-off',
    keywords: ['wifi', 'off', 'wireless', 'network'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'SignalIcon',
    exportName: 'SignalIcon',
    name: 'signal',
    keywords: ['signal', 'network', 'bars', 'connection'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'BatteryIcon',
    exportName: 'BatteryIcon',
    name: 'battery',
    keywords: ['battery', 'power', 'device', 'charge'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'BatteryChargingIcon',
    exportName: 'BatteryChargingIcon',
    name: 'battery-charging',
    keywords: ['battery', 'charging', 'power', 'device'],
    category: 'media-devices',
    status: 'ready',
  },
  {
    componentName: 'CartIcon',
    exportName: 'CartIcon',
    name: 'cart',
    keywords: ['cart', 'shop', 'commerce', 'buy'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'ShoppingBagIcon',
    exportName: 'ShoppingBagIcon',
    name: 'shopping-bag',
    keywords: ['shopping', 'bag', 'commerce', 'store'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'CreditCardIcon',
    exportName: 'CreditCardIcon',
    name: 'credit-card',
    keywords: ['credit', 'card', 'payment', 'billing'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'WalletIcon',
    exportName: 'WalletIcon',
    name: 'wallet',
    keywords: ['wallet', 'payment', 'money', 'finance'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'BanknoteIcon',
    exportName: 'BanknoteIcon',
    name: 'banknote',
    keywords: ['banknote', 'cash', 'money', 'finance'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'CoinsIcon',
    exportName: 'CoinsIcon',
    name: 'coins',
    keywords: ['coins', 'money', 'cash', 'finance'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'DollarSignIcon',
    exportName: 'DollarSignIcon',
    name: 'dollar-sign',
    keywords: ['dollar', 'currency', 'money', 'price'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'EuroIcon',
    exportName: 'EuroIcon',
    name: 'euro',
    keywords: ['euro', 'currency', 'money', 'price'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'PoundSterlingIcon',
    exportName: 'PoundSterlingIcon',
    name: 'pound-sterling',
    keywords: ['pound', 'sterling', 'currency', 'money'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'IndianRupeeIcon',
    exportName: 'IndianRupeeIcon',
    name: 'indian-rupee',
    keywords: ['rupee', 'currency', 'money', 'finance'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'PercentIcon',
    exportName: 'PercentIcon',
    name: 'percent',
    keywords: ['percent', 'discount', 'ratio', 'finance'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'ReceiptTextIcon',
    exportName: 'ReceiptTextIcon',
    name: 'receipt-text',
    keywords: ['receipt', 'text', 'bill', 'invoice'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'CalculatorIcon',
    exportName: 'CalculatorIcon',
    name: 'calculator',
    keywords: ['calculator', 'math', 'finance', 'numbers'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'GiftIcon',
    exportName: 'GiftIcon',
    name: 'gift',
    keywords: ['gift', 'present', 'commerce', 'reward'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'TicketIcon',
    exportName: 'TicketIcon',
    name: 'ticket',
    keywords: ['ticket', 'coupon', 'event', 'commerce'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'BadgePercentIcon',
    exportName: 'BadgePercentIcon',
    name: 'badge-percent',
    keywords: ['badge', 'percent', 'discount', 'sale'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'StoreIcon',
    exportName: 'StoreIcon',
    name: 'store',
    keywords: ['store', 'shop', 'commerce', 'retail'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'PackageCheckIcon',
    exportName: 'PackageCheckIcon',
    name: 'package-check',
    keywords: ['package', 'check', 'delivery', 'commerce'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'PackageXIcon',
    exportName: 'PackageXIcon',
    name: 'package-x',
    keywords: ['package', 'x', 'delivery', 'commerce'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'TruckIcon',
    exportName: 'TruckIcon',
    name: 'truck',
    keywords: ['truck', 'delivery', 'shipping', 'logistics'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'MapPinIcon',
    exportName: 'MapPinIcon',
    name: 'map-pin',
    keywords: ['map', 'pin', 'location', 'place'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'MapIcon',
    exportName: 'MapIcon',
    name: 'map',
    keywords: ['map', 'location', 'navigation', 'geo'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'NavigationIcon',
    exportName: 'NavigationIcon',
    name: 'navigation',
    keywords: ['navigation', 'direction', 'geo', 'travel'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'GlobeIcon',
    exportName: 'GlobeIcon',
    name: 'globe',
    keywords: ['globe', 'world', 'geo', 'internet'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'BuildingIcon',
    exportName: 'BuildingIcon',
    name: 'building',
    keywords: ['building', 'office', 'company', 'business'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'BriefcaseIcon',
    exportName: 'BriefcaseIcon',
    name: 'briefcase',
    keywords: ['briefcase', 'work', 'business', 'company'],
    category: 'commerce-finance',
    status: 'ready',
  },
  {
    componentName: 'LayoutGridIcon',
    exportName: 'LayoutGridIcon',
    name: 'layout-grid',
    keywords: ['layout', 'grid', 'dashboard', 'ui'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'LayoutListIcon',
    exportName: 'LayoutListIcon',
    name: 'layout-list',
    keywords: ['layout', 'list', 'rows', 'ui'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'LayoutColumnsIcon',
    exportName: 'LayoutColumnsIcon',
    name: 'layout-columns',
    keywords: ['layout', 'columns', 'split', 'ui'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'LayoutRowsIcon',
    exportName: 'LayoutRowsIcon',
    name: 'layout-rows',
    keywords: ['layout', 'rows', 'stack', 'ui'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'TableIcon',
    exportName: 'TableIcon',
    name: 'table',
    keywords: ['table', 'grid', 'data', 'rows'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'KanbanIcon',
    exportName: 'KanbanIcon',
    name: 'kanban',
    keywords: ['kanban', 'board', 'tasks', 'workflow'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ListIcon',
    exportName: 'ListIcon',
    name: 'list',
    keywords: ['list', 'items', 'rows', 'data'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ListChecksIcon',
    exportName: 'ListChecksIcon',
    name: 'list-checks',
    keywords: ['list', 'checks', 'tasks', 'todo'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ColumnsIcon',
    exportName: 'ColumnsIcon',
    name: 'columns',
    keywords: ['columns', 'layout', 'split', 'data'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'RowsIcon',
    exportName: 'RowsIcon',
    name: 'rows',
    keywords: ['rows', 'layout', 'table', 'data'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'Grid2x2Icon',
    exportName: 'Grid2x2Icon',
    name: 'grid-2x2',
    keywords: ['grid', '2x2', 'layout', 'dashboard'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'Grid3x3Icon',
    exportName: 'Grid3x3Icon',
    name: 'grid-3x3',
    keywords: ['grid', '3x3', 'layout', 'dashboard'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ChartBarIcon',
    exportName: 'ChartBarIcon',
    name: 'chart-bar',
    keywords: ['chart', 'bar', 'analytics', 'data'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ChartColumnIcon',
    exportName: 'ChartColumnIcon',
    name: 'chart-column',
    keywords: ['chart', 'column', 'analytics', 'data'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ChartLineIcon',
    exportName: 'ChartLineIcon',
    name: 'chart-line',
    keywords: ['chart', 'line', 'analytics', 'trend'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ChartPieIcon',
    exportName: 'ChartPieIcon',
    name: 'chart-pie',
    keywords: ['chart', 'pie', 'analytics', 'share'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'TrendingUpIcon',
    exportName: 'TrendingUpIcon',
    name: 'trending-up',
    keywords: ['trend', 'up', 'growth', 'analytics'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'TrendingDownIcon',
    exportName: 'TrendingDownIcon',
    name: 'trending-down',
    keywords: ['trend', 'down', 'decline', 'analytics'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'EqualIcon',
    exportName: 'EqualIcon',
    name: 'equal',
    keywords: ['equal', 'same', 'balance', 'compare'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'FunnelIcon',
    exportName: 'FunnelIcon',
    name: 'funnel',
    keywords: ['funnel', 'filter', 'pipeline', 'data'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'SortAscIcon',
    exportName: 'SortAscIcon',
    name: 'sort-asc',
    keywords: ['sort', 'asc', 'order', 'data'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'SortDescIcon',
    exportName: 'SortDescIcon',
    name: 'sort-desc',
    keywords: ['sort', 'desc', 'order', 'data'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ArrowUpDownIcon',
    exportName: 'ArrowUpDownIcon',
    name: 'arrow-up-down',
    keywords: ['arrow', 'up', 'down', 'sort'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'DatabaseIcon',
    exportName: 'DatabaseIcon',
    name: 'database',
    keywords: ['database', 'storage', 'sql', 'server'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'ServerIcon',
    exportName: 'ServerIcon',
    name: 'server',
    keywords: ['server', 'backend', 'infra', 'compute'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'HardDriveIcon',
    exportName: 'HardDriveIcon',
    name: 'hard-drive',
    keywords: ['drive', 'storage', 'disk', 'hardware'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'CpuIcon',
    exportName: 'CpuIcon',
    name: 'cpu',
    keywords: ['cpu', 'chip', 'processor', 'hardware'],
    category: 'data-layout',
    status: 'ready',
  },
  {
    componentName: 'FileIcon',
    exportName: 'FileIcon',
    name: 'file',
    keywords: ['file', 'document', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileTextIcon',
    exportName: 'FileTextIcon',
    name: 'file-text',
    keywords: ['file', 'text', 'document', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileCodeIcon',
    exportName: 'FileCodeIcon',
    name: 'file-code',
    keywords: ['file', 'code', 'dev', 'document'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileJsonIcon',
    exportName: 'FileJsonIcon',
    name: 'file-json',
    keywords: ['file', 'json', 'data', 'document'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileSpreadsheetIcon',
    exportName: 'FileSpreadsheetIcon',
    name: 'file-spreadsheet',
    keywords: ['file', 'spreadsheet', 'sheet', 'table'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileImageIcon',
    exportName: 'FileImageIcon',
    name: 'file-image',
    keywords: ['file', 'image', 'photo', 'media'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileVideoIcon',
    exportName: 'FileVideoIcon',
    name: 'file-video',
    keywords: ['file', 'video', 'media', 'movie'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileAudioIcon',
    exportName: 'FileAudioIcon',
    name: 'file-audio',
    keywords: ['file', 'audio', 'music', 'media'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileArchiveIcon',
    exportName: 'FileArchiveIcon',
    name: 'file-archive',
    keywords: ['file', 'archive', 'zip', 'compressed'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FilePlusIcon',
    exportName: 'FilePlusIcon',
    name: 'file-plus',
    keywords: ['file', 'plus', 'add', 'new'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileMinusIcon',
    exportName: 'FileMinusIcon',
    name: 'file-minus',
    keywords: ['file', 'minus', 'remove', 'delete'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FileXIcon',
    exportName: 'FileXIcon',
    name: 'file-x',
    keywords: ['file', 'x', 'remove', 'delete'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FolderIcon',
    exportName: 'FolderIcon',
    name: 'folder',
    keywords: ['folder', 'directory', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FolderOpenIcon',
    exportName: 'FolderOpenIcon',
    name: 'folder-open',
    keywords: ['folder', 'open', 'directory', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FolderPlusIcon',
    exportName: 'FolderPlusIcon',
    name: 'folder-plus',
    keywords: ['folder', 'plus', 'add', 'directory'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'FolderMinusIcon',
    exportName: 'FolderMinusIcon',
    name: 'folder-minus',
    keywords: ['folder', 'minus', 'remove', 'directory'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'ArchiveIcon',
    exportName: 'ArchiveIcon',
    name: 'archive',
    keywords: ['archive', 'box', 'storage', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'PackageIcon',
    exportName: 'PackageIcon',
    name: 'package',
    keywords: ['package', 'bundle', 'box', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'BoxIcon',
    exportName: 'BoxIcon',
    name: 'box',
    keywords: ['box', 'package', 'container', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'ReceiptIcon',
    exportName: 'ReceiptIcon',
    name: 'receipt',
    keywords: ['receipt', 'bill', 'invoice', 'document'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'BookmarkIcon',
    exportName: 'BookmarkIcon',
    name: 'bookmark',
    keywords: ['bookmark', 'save', 'mark', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'BookOpenIcon',
    exportName: 'BookOpenIcon',
    name: 'book-open',
    keywords: ['book', 'open', 'read', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'NewspaperIcon',
    exportName: 'NewspaperIcon',
    name: 'newspaper',
    keywords: ['news', 'paper', 'article', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'StickyNoteIcon',
    exportName: 'StickyNoteIcon',
    name: 'sticky-note',
    keywords: ['sticky', 'note', 'memo', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'TagIcon',
    exportName: 'TagIcon',
    name: 'tag',
    keywords: ['tag', 'label', 'category', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'TagsIcon',
    exportName: 'TagsIcon',
    name: 'tags',
    keywords: ['tags', 'labels', 'categories', 'content'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'PaperclipIcon',
    exportName: 'PaperclipIcon',
    name: 'paperclip',
    keywords: ['paperclip', 'attach', 'clip', 'file'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'ImageIcon',
    exportName: 'ImageIcon',
    name: 'image',
    keywords: ['image', 'photo', 'picture', 'media'],
    category: 'files-content',
    status: 'ready',
  },
  {
    componentName: 'ChevronsUpIcon',
    exportName: 'ChevronsUpIcon',
    name: 'chevrons-up',
    keywords: ['chevrons', 'up', 'double', 'direction'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ChevronsDownIcon',
    exportName: 'ChevronsDownIcon',
    name: 'chevrons-down',
    keywords: ['chevrons', 'down', 'double', 'direction'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ChevronsLeftIcon',
    exportName: 'ChevronsLeftIcon',
    name: 'chevrons-left',
    keywords: ['chevrons', 'left', 'double', 'direction'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ChevronsRightIcon',
    exportName: 'ChevronsRightIcon',
    name: 'chevrons-right',
    keywords: ['chevrons', 'right', 'double', 'direction'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ExpandIcon',
    exportName: 'ExpandIcon',
    name: 'expand',
    keywords: ['expand', 'fullscreen', 'grow', 'maximize'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'ShrinkIcon',
    exportName: 'ShrinkIcon',
    name: 'shrink',
    keywords: ['shrink', 'collapse', 'reduce', 'minimize'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'PanelLeftIcon',
    exportName: 'PanelLeftIcon',
    name: 'panel-left',
    keywords: ['panel', 'left', 'layout', 'sidebar'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'PanelRightIcon',
    exportName: 'PanelRightIcon',
    name: 'panel-right',
    keywords: ['panel', 'right', 'layout', 'sidebar'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'SidebarOpenIcon',
    exportName: 'SidebarOpenIcon',
    name: 'sidebar-open',
    keywords: ['sidebar', 'open', 'panel', 'layout'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'SidebarCloseIcon',
    exportName: 'SidebarCloseIcon',
    name: 'sidebar-close',
    keywords: ['sidebar', 'close', 'panel', 'layout'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'EllipsisIcon',
    exportName: 'EllipsisIcon',
    name: 'ellipsis',
    keywords: ['ellipsis', 'more', 'overflow', 'menu'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'SwapHorizontalIcon',
    exportName: 'SwapHorizontalIcon',
    name: 'swap-horizontal',
    keywords: ['swap', 'horizontal', 'switch', 'exchange'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'SwapVerticalIcon',
    exportName: 'SwapVerticalIcon',
    name: 'swap-vertical',
    keywords: ['swap', 'vertical', 'switch', 'exchange'],
    category: 'navigation-direction',
    status: 'ready',
  },
  {
    componentName: 'RotateCwIcon',
    exportName: 'RotateCwIcon',
    name: 'rotate-cw',
    keywords: ['rotate', 'cw', 'clockwise', 'refresh'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'RotateCcwIcon',
    exportName: 'RotateCcwIcon',
    name: 'rotate-ccw',
    keywords: ['rotate', 'ccw', 'counterclockwise', 'refresh'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'FilterIcon',
    exportName: 'FilterIcon',
    name: 'filter',
    keywords: ['filter', 'sort', 'criteria', 'refine'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'SlidersHorizontalIcon',
    exportName: 'SlidersHorizontalIcon',
    name: 'sliders-horizontal',
    keywords: ['sliders', 'horizontal', 'controls', 'settings'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'SlidersVerticalIcon',
    exportName: 'SlidersVerticalIcon',
    name: 'sliders-vertical',
    keywords: ['sliders', 'vertical', 'controls', 'settings'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'WandIcon',
    exportName: 'WandIcon',
    name: 'wand',
    keywords: ['wand', 'magic', 'tool', 'edit'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'SparklesIcon',
    exportName: 'SparklesIcon',
    name: 'sparkles',
    keywords: ['sparkles', 'magic', 'highlight', 'ai'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ZoomInIcon',
    exportName: 'ZoomInIcon',
    name: 'zoom-in',
    keywords: ['zoom', 'in', 'magnify', 'search'],
    category: 'actions-editing',
    status: 'ready',
  },
  {
    componentName: 'ZoomOutIcon',
    exportName: 'ZoomOutIcon',
    name: 'zoom-out',
    keywords: ['zoom', 'out', 'magnify', 'search'],
    category: 'actions-editing',
    status: 'ready',
  },
] as const satisfies readonly IconManifestEntry[];
