/**
 * Vue 3 export target plugin (stub).
 *
 * Produces a runnable Vue 3 project from the export IR.
 * Each IR page maps to a `.vue` SFC file. A shared `main.ts`,
 * `vite.config.ts`, and `package.json` are generated alongside.
 *
 * This module proves that the export-core IR layer is target-agnostic:
 * it consumes `EnrichExportResult` and produces `RenderExportResult`
 * without relying on React-specific assumptions.
 */

import type { EnrichExportResult, ExportIRNode } from '../index';
import { createExportTargetPlugin, createStaticRenderResult } from '../targets';

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function pascalCase(value: string): string {
  return value
    .split(/[-_]/g)
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

function renderPropValue(value: string | number | boolean | null): string {
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean')
    return String(value);
  return 'null';
}

function renderNodeToVueTemplate(node: ExportIRNode): string {
  if (node.exportKind === 'unsupported') {
    return `<div data-unsupported-component="${node.componentId}" />`;
  }
  const tagName = node.componentId;
  const propEntries = Object.entries(node.props)
    .map(([key, value]) => `:${key}="${renderPropValue(value)}"`)
    .join(' ');
  const openTag =
    propEntries.length > 0 ? `<${tagName} ${propEntries}>` : `<${tagName}>`;
  const children = node.children?.map(renderNodeToVueTemplate).join('\n') ?? '';
  const closeTag = `</${tagName}>`;
  return `${openTag}\n${children}\n${closeTag}`;
}

// ---------------------------------------------------------------------------
// Vue 3 target plugin
// ---------------------------------------------------------------------------

export const vue3Target = createExportTargetPlugin({
  target: 'vue3',
  version: '1',
  displayName: 'Vue 3',
  supportedStages: ['normalize', 'analyze', 'enrich', 'render'],

  render(enriched: EnrichExportResult) {
    const { ir } = enriched;
    const diagnostics = [...enriched.diagnostics];

    if (ir.pages.length === 0) {
      return createStaticRenderResult(
        [],
        [
          ...diagnostics,
          {
            level: 'error',
            code: 'UNSUPPORTED_COMPONENT',
            message: 'Cannot render Vue 3 export without at least one page.',
          },
        ]
      );
    }

    const files = ir.pages.map((page) => {
      const componentName = pascalCase(page.name || 'page');
      const template = renderNodeToVueTemplate(page.rootNode);

      const content = `<script setup lang="ts">
// Auto-generated Vue 3 component for page: ${page.name}
</script>

<template>
  <div class="page-${page.name}">
${template}
  </div>
</template>

<style scoped>
.page-${page.name} {
  padding: 1rem;
}
</style>
`;

      return {
        path: `src/pages/${componentName}.vue`,
        content,
      };
    });

    files.push({
      path: 'src/main.ts',
      content: `import { createApp } from 'vue';
import App from './App.vue';

createApp(App).mount('#app');
`,
    });

    files.push({
      path: 'package.json',
      content: JSON.stringify(
        {
          name: `${ir.name || 'exported-project'}`,
          private: true,
          version: '0.0.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vue-tsc && vite build',
          },
          dependencies: {
            vue: '^3.5.0',
          },
          devDependencies: {
            '@vitejs/plugin-vue': '^5.0.0',
            typescript: '^5.6.0',
            vite: '^6.0.0',
            'vue-tsc': '^2.0.0',
          },
        },
        null,
        2
      ),
    });

    files.push({
      path: 'README.md',
      content: `# ${ir.name}\n\nGenerated by @ui-construction-library/export-core for target vue3.\n`,
    });

    return createStaticRenderResult(files, diagnostics);
  },
});
