import { createDesignTokenArtifactFiles } from './fidelity';
import { renderNodeToJsx } from './render-helpers';
import type {
  ExportDiagnostic,
  ExportFile,
  ExportIRProject,
  RenderExportResult,
} from './types';

export function renderHtmlStatic(ir: ExportIRProject): RenderExportResult {
  const diagnostics: ExportDiagnostic[] = [];

  if (ir.pages.length === 0) {
    diagnostics.push({
      level: 'error',
      code: 'UNSUPPORTED_COMPONENT',
      message: 'Cannot render export without at least one page.',
    });

    return { files: [], diagnostics };
  }

  const navigationButtons = ir.pages
    .map(
      (page) =>
        `        <button type="button" data-route=${JSON.stringify(page.path)}>${page.name}</button>`
    )
    .join('\n');

  const pageSections = ir.pages
    .map((page, index) => {
      const sectionBody = renderNodeToJsx(page.rootNode);
      const hiddenAttribute = index === 0 ? '' : ' hidden';

      return `      <section data-page-id=${JSON.stringify(page.pageId)} data-page-path=${JSON.stringify(page.path)}${hiddenAttribute}>${sectionBody}</section>`;
    })
    .join('\n');

  const files: ExportFile[] = [
    {
      path: 'index.html',
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${ir.name}</title>
    <style>
      :root { color-scheme: light; font-family: Inter, system-ui, sans-serif; }
      body { margin: 0; background: #f8fafc; color: #0f172a; }
      header { padding: 24px; border-bottom: 1px solid #e2e8f0; background: #ffffff; }
      nav { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 16px; }
      button { border-radius: 999px; border: 1px solid #cbd5e1; background: #ffffff; padding: 8px 14px; cursor: pointer; }
      main { padding: 24px; }
      section[hidden] { display: none; }
    </style>
  </head>
  <body>
    <header>
      <strong>${ir.name}</strong>
      <nav aria-label="Exported pages">
${navigationButtons}
      </nav>
    </header>
    <main data-project-id=${JSON.stringify(ir.projectId)}>
${pageSections}
    </main>
    <script>
      const buttons = Array.from(document.querySelectorAll('[data-route]'));
      const sections = Array.from(document.querySelectorAll('section[data-page-id]'));
      buttons.forEach((button) => {
        button.addEventListener('click', () => {
          const nextRoute = button.getAttribute('data-route');
          sections.forEach((section) => {
            section.hidden = section.getAttribute('data-page-path') !== nextRoute;
          });
        });
      });
    </script>
  </body>
</html>
`,
    },
    ...createDesignTokenArtifactFiles(),
    {
      path: 'README.md',
      content: `# ${ir.name}\n\nGenerated by @ui-construction-library/export-core for target ${ir.target}.\n`,
    },
  ];

  return { files, diagnostics };
}
