import { createDesignTokenArtifactFiles } from './fidelity';
import {
  collectExportedComponentIds,
  createCoreComponentImportStatement,
  renderNodeToJsx,
} from './render-helpers';
import type {
  ExportDiagnostic,
  ExportFile,
  ExportIRProject,
  RenderExportResult,
} from './types';

function createNextAppRouterFilePath(pagePath: string): string {
  const normalized = pagePath.trim();
  if (normalized === '/' || normalized === '') return 'app/page.tsx';
  const segments = normalized
    .split('/')
    .map((segment) => segment.trim())
    .filter(Boolean)
    .map((segment) =>
      segment
        .toLowerCase()
        .replace(/[^a-z0-9-]+/g, '-')
        .replace(/^-|-$/g, '')
    )
    .filter(Boolean);
  if (segments.length === 0) return 'app/page.tsx';
  return `app/${segments.join('/')}/page.tsx`;
}

export function renderNextjsAppRouter(ir: ExportIRProject): RenderExportResult {
  const diagnostics: ExportDiagnostic[] = [];
  const componentIds = collectExportedComponentIds(ir);
  const componentImports = createCoreComponentImportStatement(componentIds);

  if (ir.pages.length === 0) {
    diagnostics.push({
      level: 'error',
      code: 'UNSUPPORTED_COMPONENT',
      message: 'Cannot render export without at least one page.',
    });

    return { files: [], diagnostics };
  }

  const baseDependencies = new Set<string>(['next', 'react', 'react-dom']);
  for (const id of componentIds) {
    if (id) baseDependencies.add('@ui-construction-library/core');
  }
  if (componentIds.length > 1) baseDependencies.add('clsx');
  const dependencyVersions: Record<string, string> = {
    next: '^15.3.0',
    react: '^18.3.1',
    'react-dom': '^18.3.1',
    '@ui-construction-library/core': '^0.0.0',
    clsx: '^2.1.1',
  };
  const dependencies = Object.fromEntries(
    [...baseDependencies]
      .sort()
      .map((name) => [name, dependencyVersions[name] ?? '^0.0.0'])
  );

  const files: ExportFile[] = [
    {
      path: 'package.json',
      content: `${JSON.stringify(
        {
          name: 'exported-ui-project-next',
          private: true,
          version: '0.1.0',
          scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
          },
          dependencies,
        },
        null,
        2
      )}\n`,
    },
    {
      path: 'tsconfig.json',
      content: `${JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            lib: ['DOM', 'DOM.Iterable', 'ES2020'],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'ESNext',
            moduleResolution: 'Bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
          },
          include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
          exclude: ['node_modules'],
        },
        null,
        2
      )}\n`,
    },
    {
      path: 'next-env.d.ts',
      content:
        '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// NOTE: This file should not be edited\n\n',
    },
    {
      path: 'next.config.mjs',
      content: 'export default {};\n',
    },
    {
      path: 'app/globals.css',
      content:
        ':root { --export-font-sans: Inter, system-ui, sans-serif; --export-bg: #f8fafc; --export-surface: #ffffff; --export-border: #e2e8f0; --export-text: #0f172a; --export-muted: #475569; --export-accent: #0f766e; }\n* { box-sizing: border-box; }\nhtml, body { margin: 0; min-height: 100%; font-family: var(--export-font-sans); background: var(--export-bg); color: var(--export-text); }\nmain { padding: 32px; }\n',
    },
    {
      path: 'app/layout.tsx',
      content:
        'import \'./globals.css\';\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode;\n}) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n',
    },
    ...ir.pages
      .map((page) => {
        const jsx = renderNodeToJsx(page.rootNode);
        const filePath = createNextAppRouterFilePath(page.path);
        return {
          path: filePath,
          content: `${componentImports}\nexport default function Page() {\n  return (\n    <main data-project-id=${JSON.stringify(ir.projectId)} data-page-id=${JSON.stringify(page.pageId)} data-page-path=${JSON.stringify(page.path)}>\n      ${jsx}\n    </main>\n  );\n}\n`,
        };
      })
      .sort((a, b) => a.path.localeCompare(b.path)),
    ...createDesignTokenArtifactFiles(),
    {
      path: 'README.md',
      content: `# ${ir.name}\n\nGenerated by @ui-construction-library/export-core for target ${ir.target}.\n`,
    },
  ];

  return { files, diagnostics };
}
