import { createDesignTokenArtifactFiles } from './fidelity';
import type {
  ExportDiagnostic,
  ExportFile,
  ExportIRNode,
  ExportIRProject,
  RenderExportResult,
} from './types';

function createCustomElementTag(componentId: string): string {
  return `ui-${componentId.replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
}

function renderPropsToDataset(
  props: Record<string, string | number | boolean | null>
): string {
  const entries = Object.entries(props)
    .filter(([, value]) => value !== null)
    .map(
      ([key, value]) =>
        ` data-prop-${key.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}=${JSON.stringify(String(value))}`
    );

  return entries.join('');
}

function renderNodeToCustomElement(node: ExportIRNode): string {
  if (node.exportKind === 'unsupported') {
    return `<div data-unsupported-component=${JSON.stringify(node.componentId)}></div>`;
  }

  const tagName = createCustomElementTag(node.componentId);
  const dataset = renderPropsToDataset(node.props);
  const children = node.children
    .map((child) => renderNodeToCustomElement(child))
    .join('');

  return `<${tagName}${dataset}>${children}</${tagName}>`;
}

export function renderWebComponentsStatic(
  ir: ExportIRProject
): RenderExportResult {
  const diagnostics: ExportDiagnostic[] = [];

  if (ir.pages.length === 0) {
    diagnostics.push({
      level: 'error',
      code: 'UNSUPPORTED_COMPONENT',
      message: 'Cannot render export without at least one page.',
    });

    return { files: [], diagnostics };
  }

  const pageButtons = ir.pages
    .map(
      (page) =>
        `        <button type="button" data-route=${JSON.stringify(page.path)}>${page.name}</button>`
    )
    .join('\n');

  const pageMarkup = ir.pages
    .map((page, index) => {
      const hiddenAttribute = index === 0 ? '' : ' hidden';
      return `      <section data-page-id=${JSON.stringify(page.pageId)} data-page-path=${JSON.stringify(page.path)}${hiddenAttribute}>${renderNodeToCustomElement(page.rootNode)}</section>`;
    })
    .join('\n');

  const files: ExportFile[] = [
    {
      path: 'index.html',
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${ir.name}</title>
    <script type="module" src="./components.js"></script>
    <style>
      :root { color-scheme: light; font-family: Inter, system-ui, sans-serif; }
      body { margin: 0; background: #f8fafc; color: #0f172a; }
      header { padding: 24px; border-bottom: 1px solid #e2e8f0; background: #ffffff; }
      nav { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 16px; }
      button { border-radius: 999px; border: 1px solid #cbd5e1; background: #ffffff; padding: 8px 14px; cursor: pointer; }
      main { padding: 24px; }
      section[hidden] { display: none; }
      ui-card, ui-heading, ui-text { display: block; }
    </style>
  </head>
  <body>
    <header>
      <strong>${ir.name}</strong>
      <nav aria-label="Exported pages">
${pageButtons}
      </nav>
    </header>
    <main data-project-id=${JSON.stringify(ir.projectId)}>
${pageMarkup}
    </main>
    <script>
      const buttons = Array.from(document.querySelectorAll('[data-route]'));
      const sections = Array.from(document.querySelectorAll('section[data-page-id]'));
      buttons.forEach((button) => {
        button.addEventListener('click', () => {
          const nextRoute = button.getAttribute('data-route');
          sections.forEach((section) => {
            section.hidden = section.getAttribute('data-page-path') !== nextRoute;
          });
        });
      });
    </script>
  </body>
</html>
`,
    },
    {
      path: 'components.js',
      content: `class UiCard extends HTMLElement {
  connectedCallback() {
    this.style.display = 'block';
    this.style.padding = '16px';
    this.style.border = '1px solid #cbd5e1';
    this.style.borderRadius = '16px';
    this.style.background = '#ffffff';
  }
}

class UiHeading extends HTMLElement {
  connectedCallback() {
    const text = this.getAttribute('data-prop-children') ?? '';
    const level = this.getAttribute('data-prop-level') ?? '2';
    this.innerHTML = '<h' + level + '>' + text + '</h' + level + '>';
  }
}

class UiText extends HTMLElement {
  connectedCallback() {
    const text = this.getAttribute('data-prop-children') ?? '';
    this.innerHTML = '<p>' + text + '</p>';
  }
}

customElements.define('ui-card', UiCard);
customElements.define('ui-heading', UiHeading);
customElements.define('ui-text', UiText);
`,
    },
    ...createDesignTokenArtifactFiles(),
    {
      path: 'README.md',
      content: `# ${ir.name}\n\nGenerated by @ui-construction-library/export-core for target ${ir.target}.\n`,
    },
  ];

  return { files, diagnostics };
}
